version: "3"
services:
  sass:
    image: "sassv1"
    ports:
      - "80:5000"
    networks: 
      - backend

  mongo:
    image: "mongosass"
    networks:
      - backend
networks:
  backend:
    external: true
