version: "3"
services:
  sass:
    container_name: backend
    image: "sassv1"
    ports:
      - "443:5000"
    networks: 
      backend:
        ipv4_address: 10.5.0.7

  mongo:
    container_name: mongosass
    image: "a19matrivort/mongosass"
    ports:
      - "27017:27017"
    networks:
      backend:
        ipv4_address: 10.5.0.6

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
