version: "3"
services:
  sass:
    container_name: backend
    image: "stacksassimg"
    ports:
      - "443:5000"
      - "1234:1234"
    environment:
      - MONGO_URL=mongosass
      - REACT_APP_FRONT_URL=${REACT_APP_FRONT_URL}
    networks: 
      backend:
        ipv4_address: 10.5.0.7

  mongo:
    container_name: mongosass
    image: "mongosassimg"
    networks:
      backend:
        ipv4_address: 10.5.0.6

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
