version: "3"
services:
  sass:
    container_name: backend
    image: "38f7d469ef48"
    ports:
      - "443:5000"
      - "1234:1234"
    environment:
      - MONGO_URL=mongosass
    networks: 
      backend:
        ipv4_address: 10.5.0.7

  mongo:
    container_name: mongosass
    image: "2691853d2bcf"
    networks:
      backend:
        ipv4_address: 10.5.0.6

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
